### ISSUE TITLE
[FORGE 1.19.2] Complex conflict

### ISSUE THREAD

**Issue by Aulberon** [Majrusz/MajruszsAccessories#7]
When using this mod, curios and smooth swap and having a modified number of curios slots the game CTD when I scroll the curios screen.

[CrashLog](https://hastebin.com/izirewulan.properties)
[Latest.log](https://hastebin.com/equjuvajaj.sql)
[Modified curios-server config](https://hastebin.com/xofilijeqe.ini)

Modlist:
FORGE 43.1.52
curios-forge-1.19.2-5.1.1.0
majrusz-library-1.19.2-2.17.0
majruszs-accessories-1.19.2-1.1.0
Smooth Swapping-1.19.2-1.0.0

**Comment by Aulberon** [comment]
I have posted the same issue on Smooth Swapping repo:
https://github.com/baguchan/Smooth-Swapping-Forge/issues/1

**Comment by Majrusz** [comment]
Well, cannot find the exact reason why it crashes, but this class from Smooth Swapping is guilty: https://github.com/baguchan/Smooth-Swapping-Forge/blob/master/src/main/java/schauweg/smoothswapping/mixin/AbstractContainerScreenMixin.java 
I believe @baguchan needs to adjust their mod to work with custom curios slots. Until the issue is resolved, I am leaving the thread open
